### ISSUE TITLE
Support for GitHub repo which has 2-way Authentication

### ISSUE THREAD

**Issue by rajeev-daishogroup** [jonnyzzz/TeamCity.GitHub#118]
I have a Github account which has 2-way Authentication enabled. After I configured the plugin, I couldn't see the Build status from Teamcity sent back to GitHub. In the Teamcity server logs I can see the following error msgs :
```
[2018-05-28 08:11:22,393]   INFO - lty.github.ChangeStatusUpdater - Scheduling GitHub status update for hash: 4da3961f5dbecd1a25effe5610152d5df5d582d3af, branch: refs/pull/4/head, buildId: 10826, status: Pending 
[2018-05-28 08:11:22,734]   WARN - .github.api.impl.GitHubApiImpl - Failed to complete query to GitHub with:
  requestURL: https://api.github.com/repos/XX-XX/XX/statuses/4da3961f5dbecd1a25effe5610152d5df5d582d3af
  requestMethod: POST
  requestEntity: {"state":"pending","target_url":"https://teamcity.daisho.group/viewLog.html?buildId\u003d10826\u0026buildTypeId\u003dTest_Build","description":"Started TeamCity Build Test :: Build"}
  response: HTTP/1.1 401 Unauthorized
  responseEntity: {"message":"**Must specify two-factor authentication OTP** code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"} 
[2018-05-28 08:11:22,738]   WARN - lty.github.ChangeStatusUpdater - Failed to update GitHub status for hash: 4da3961f5dbecd1a25effe50a52d5df5d582d3af, buildId: 10826, status: Pending. Failed to complete request to GitHub. Status: HTTP/1.1 401 Unauthorized 
java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 401 Unauthorized
	at jetbrains.teamcilty.github.api.impl.GitHubApiImpl.setChangeStatus(GitHubApiImpl.java:131)
	at jetbrains.teamcilty.github.ChangeStatusUpdater$1$1.run(ChangeStatusUpdater.java:272)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:71)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-28 08:11:29,358]   INFO -   jetbrains.buildServer.SERVER - Build finished received for build: #9 {build id=10826, buildTypeId=Test_Build} 
```

**Comment by jonnyzzz** [comment]
t does not look like the feature is supported by the plugin. You may
probably use auth token instead. Also, there is a similar functionality
embedded in fresh versions of TeamCity. You may probably consider checking
if it works there or contribute the fix here.

>
