### ISSUE TITLE
404 error when updating Status

### ISSUE THREAD

**Issue by MarkDordoy-JustEat** [jonnyzzz/TeamCity.GitHub#82]
Im running the plugin version 0.5.92 and have teamcity version 9.0.4 with github enterprise 2.1.5 and since we upgraded teamcity i believe this problem has existed. 

an example error is 
[2015-06-09 16:03:42,697]   WARN - lty.github.ChangeStatusUpdater - Failed to update GitHub status for hash: 1ab07f0d4f431caa48e43da995b52a42f2715cb4, buildId: 1283838, status: Pending. Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found 
java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found
	at jetbrains.teamcilty.github.api.impl.GitHubApiImpl.setChangeStatus(GitHubApiImpl.java:131)
	at jetbrains.teamcilty.github.ChangeStatusUpdater$1$1.run(ChangeStatusUpdater.java:272)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Has the plugin been tested with the versions of the applications listed above?

**Comment by jonnyzzz** [comment]
Hello,

It looks like a permission issue. Could you please check the repo is
visible and write-accessible to the user account used in the build feature.

You may also make sure GitHub enterprise api url is correct. You may check
the url via curl

**Comment by MarkDordoy-JustEat** [comment]
Hello

Ive been looking into this a little deeper and there is something strange going on. 

I ran a build with the plugin using an account that is an owner, i can see the comments being added to github, but it seems to be grabbing two commit ID's but one just doesnt exist. 

```
[2015-06-11 11:24:56,932]   INFO - lty.github.ChangeStatusUpdater - Updated GitHub status for hash: e6ed7fe06894d6a9b5afbadf763018fac4ab07cf, buildId: 1287992, status: Failure 
[2015-06-11 11:24:57,057]   WARN - .github.api.impl.GitHubApiImpl - Failed to complete query to GitHub with:
  requestURL: https://github.je-labs.com/api/v3/repos/BAPPS/app_newguard/commits/b22115f3e971648c7fc6acf23b6c52ed5b08c045/comments
  requestMethod: POST
  requestEntity: {"body":"TeamCity Business Applications :: NewGuard :: QA10 Functional Tests [Build 1.0.0.49](http://ci.je-labs.com/viewLog.html?buildId\u003d1287992\u0026buildTypeId\u003dBappsNewGuard_02qa9FunctionalTestsNewScripts) outcome was **FAILURE**\nSummary: Tests failed: 1, passed: 24, ignored: 1 Build time: 00:06:26\n### Failed tests\n```\nJustEat.NewGuard.Site.Acceptance.dll: JustEat.NewGuard.Site.Acceptance.Features.OrderPagingFeature.SettingOrdersLimitToShow100ShouldDisplayOnlyFirst100OrdersAndHideTheRest: \u003cno details avaliable\u003e\n\n```\n"}
  response: HTTP/1.1 404 Not Found
  responseEntity: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.1/v3"} 
[2015-06-11 11:24:57,057]   WARN - lty.github.ChangeStatusUpdater - Failed add GitHub comment for branch: refs/heads/master, buildId: 1287992, status: Failure. Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found 
java.io.IOException: Failed to complete request to GitHub. Status: HTTP/1.1 404 Not Found
	at jetbrains.teamcilty.github.api.impl.GitHubApiImpl.postComment(GitHubApiImpl.java:301)
	at jetbrains.teamcilty.github.ChangeStatusUpdater$1$1.run(ChangeStatusUpdater.java:287)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```
CommitID e6ed7fe06894d6a9b5afbadf763018fac4ab07cf is valid and showing the comments as expected, but CommitID b22115f3e971648c7fc6acf23b6c52ed5b08c045 doesnt exist and i have no idea where its getting it from.

**Comment by jonnyzzz** [comment]
How have you set up branches in build. This looks like you use 'merge' in
pull request branch name. Switching to 'head' should solve it

**Comment by MarkDordoy-JustEat** [comment]
we ideally need it to work with pull requests as well as heads

**Comment by jonnyzzz** [comment]
It works with pull requests
Could you please share settings you use in VCS root. What I need to check
are branch spec you use
